// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/nefi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Connections   []*ConnectionEvent     `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	HttpRequests  []*HTTPRequestEvent    `protobuf:"bytes,3,rep,name=http_requests,json=httpRequests,proto3" json:"http_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_internal_proto_nefi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_nefi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_internal_proto_nefi_proto_rawDescGZIP(), []int{0}
}

func (x *EventBatch) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *EventBatch) GetConnections() []*ConnectionEvent {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *EventBatch) GetHttpRequests() []*HTTPRequestEvent {
	if x != nil {
		return x.HttpRequests
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_internal_proto_nefi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_nefi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_nefi_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *StreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EndpointProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Pod           string                 `protobuf:"bytes,3,opt,name=pod,proto3" json:"pod,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Workload      string                 `protobuf:"bytes,5,opt,name=workload,proto3" json:"workload,omitempty"`
	WorkloadType  string                 `protobuf:"bytes,6,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"`
	Service       string                 `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointProto) Reset() {
	*x = EndpointProto{}
	mi := &file_internal_proto_nefi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointProto) ProtoMessage() {}

func (x *EndpointProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_nefi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointProto.ProtoReflect.Descriptor instead.
func (*EndpointProto) Descriptor() ([]byte, []int) {
	return file_internal_proto_nefi_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointProto) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EndpointProto) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointProto) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *EndpointProto) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EndpointProto) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *EndpointProto) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

func (x *EndpointProto) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ConnectionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Source        *EndpointProto         `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   *EndpointProto         `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,6,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	DurationNs    uint64                 `protobuf:"varint,7,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Retransmits   uint32                 `protobuf:"varint,8,opt,name=retransmits,proto3" json:"retransmits,omitempty"`
	Protocol      string                 `protobuf:"bytes,9,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionEvent) Reset() {
	*x = ConnectionEvent{}
	mi := &file_internal_proto_nefi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionEvent) ProtoMessage() {}

func (x *ConnectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_nefi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionEvent.ProtoReflect.Descriptor instead.
func (*ConnectionEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_nefi_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ConnectionEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ConnectionEvent) GetSource() *EndpointProto {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ConnectionEvent) GetDestination() *EndpointProto {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *ConnectionEvent) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ConnectionEvent) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *ConnectionEvent) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *ConnectionEvent) GetRetransmits() uint32 {
	if x != nil {
		return x.Retransmits
	}
	return 0
}

func (x *ConnectionEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type HTTPRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Source        *EndpointProto         `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   *EndpointProto         `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyNs     uint64                 `protobuf:"varint,8,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	Protocol      string                 `protobuf:"bytes,9,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequestEvent) Reset() {
	*x = HTTPRequestEvent{}
	mi := &file_internal_proto_nefi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestEvent) ProtoMessage() {}

func (x *HTTPRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_nefi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestEvent.ProtoReflect.Descriptor instead.
func (*HTTPRequestEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_nefi_proto_rawDescGZIP(), []int{4}
}

func (x *HTTPRequestEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *HTTPRequestEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *HTTPRequestEvent) GetSource() *EndpointProto {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *HTTPRequestEvent) GetDestination() *EndpointProto {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *HTTPRequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequestEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequestEvent) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPRequestEvent) GetLatencyNs() uint64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *HTTPRequestEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var File_internal_proto_nefi_proto protoreflect.FileDescriptor

const file_internal_proto_nefi_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/nefi.proto\x12\bnefi\"\x9e\x01\n" +
	"\n" +
	"EventBatch\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12;\n" +
	"\vconnections\x18\x02 \x03(\v2\x19.nefi.ConnectionEventR\vconnections\x12?\n" +
	"\rhttp_requests\x18\x03 \x03(\v2\x1a.nefi.HTTPRequestEventR\fhttpRequests\"B\n" +
	"\x0eStreamResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xbe\x01\n" +
	"\rEndpointProto\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x10\n" +
	"\x03pod\x18\x03 \x01(\tR\x03pod\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bworkload\x18\x05 \x01(\tR\bworkload\x12#\n" +
	"\rworkload_type\x18\x06 \x01(\tR\fworkloadType\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice\"\xd1\x02\n" +
	"\x0fConnectionEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12/\n" +
	"\x06source\x18\x03 \x01(\v2\x17.nefi.EndpointProtoR\x06source\x129\n" +
	"\vdestination\x18\x04 \x01(\v2\x17.nefi.EndpointProtoR\vdestination\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x06 \x01(\x04R\tbytesRecv\x12\x1f\n" +
	"\vduration_ns\x18\a \x01(\x04R\n" +
	"durationNs\x12 \n" +
	"\vretransmits\x18\b \x01(\rR\vretransmits\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\tR\bprotocol\"\xbd\x02\n" +
	"\x10HTTPRequestEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12/\n" +
	"\x06source\x18\x03 \x01(\v2\x17.nefi.EndpointProtoR\x06source\x129\n" +
	"\vdestination\x18\x04 \x01(\v2\x17.nefi.EndpointProtoR\vdestination\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\b \x01(\x04R\tlatencyNs\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\tR\bprotocol2R\n" +
	"\x0eEventIngestion\x12@\n" +
	"\fStreamEvents\x12\x14.nefi.EventBatch\x1a\x18.nefi.StreamResponse(\x01B-Z+github.com/gihongjo/nefi/internal/protob\x06proto3"

var (
	file_internal_proto_nefi_proto_rawDescOnce sync.Once
	file_internal_proto_nefi_proto_rawDescData []byte
)

func file_internal_proto_nefi_proto_rawDescGZIP() []byte {
	file_internal_proto_nefi_proto_rawDescOnce.Do(func() {
		file_internal_proto_nefi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_nefi_proto_rawDesc), len(file_internal_proto_nefi_proto_rawDesc)))
	})
	return file_internal_proto_nefi_proto_rawDescData
}

var file_internal_proto_nefi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_nefi_proto_goTypes = []any{
	(*EventBatch)(nil),       // 0: nefi.EventBatch
	(*StreamResponse)(nil),   // 1: nefi.StreamResponse
	(*EndpointProto)(nil),    // 2: nefi.EndpointProto
	(*ConnectionEvent)(nil),  // 3: nefi.ConnectionEvent
	(*HTTPRequestEvent)(nil), // 4: nefi.HTTPRequestEvent
}
var file_internal_proto_nefi_proto_depIdxs = []int32{
	3, // 0: nefi.EventBatch.connections:type_name -> nefi.ConnectionEvent
	4, // 1: nefi.EventBatch.http_requests:type_name -> nefi.HTTPRequestEvent
	2, // 2: nefi.ConnectionEvent.source:type_name -> nefi.EndpointProto
	2, // 3: nefi.ConnectionEvent.destination:type_name -> nefi.EndpointProto
	2, // 4: nefi.HTTPRequestEvent.source:type_name -> nefi.EndpointProto
	2, // 5: nefi.HTTPRequestEvent.destination:type_name -> nefi.EndpointProto
	0, // 6: nefi.EventIngestion.StreamEvents:input_type -> nefi.EventBatch
	1, // 7: nefi.EventIngestion.StreamEvents:output_type -> nefi.StreamResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_nefi_proto_init() }
func file_internal_proto_nefi_proto_init() {
	if File_internal_proto_nefi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_nefi_proto_rawDesc), len(file_internal_proto_nefi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_nefi_proto_goTypes,
		DependencyIndexes: file_internal_proto_nefi_proto_depIdxs,
		MessageInfos:      file_internal_proto_nefi_proto_msgTypes,
	}.Build()
	File_internal_proto_nefi_proto = out.File
	file_internal_proto_nefi_proto_goTypes = nil
	file_internal_proto_nefi_proto_depIdxs = nil
}
