// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/proto/nefi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestion_StreamEvents_FullMethodName = "/nefi.EventIngestion/StreamEvents"
)

// EventIngestionClient is the client API for EventIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventIngestion service receives events from nefi-agent.
type EventIngestionClient interface {
	// StreamEvents sends a stream of events from agent to server.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventBatch, StreamResponse], error)
}

type eventIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionClient(cc grpc.ClientConnInterface) EventIngestionClient {
	return &eventIngestionClient{cc}
}

func (c *eventIngestionClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventBatch, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngestion_ServiceDesc.Streams[0], EventIngestion_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestion_StreamEventsClient = grpc.ClientStreamingClient[EventBatch, StreamResponse]

// EventIngestionServer is the server API for EventIngestion service.
// All implementations must embed UnimplementedEventIngestionServer
// for forward compatibility.
//
// EventIngestion service receives events from nefi-agent.
type EventIngestionServer interface {
	// StreamEvents sends a stream of events from agent to server.
	StreamEvents(grpc.ClientStreamingServer[EventBatch, StreamResponse]) error
	mustEmbedUnimplementedEventIngestionServer()
}

// UnimplementedEventIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServer struct{}

func (UnimplementedEventIngestionServer) StreamEvents(grpc.ClientStreamingServer[EventBatch, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventIngestionServer) mustEmbedUnimplementedEventIngestionServer() {}
func (UnimplementedEventIngestionServer) testEmbeddedByValue()                        {}

// UnsafeEventIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServer will
// result in compilation errors.
type UnsafeEventIngestionServer interface {
	mustEmbedUnimplementedEventIngestionServer()
}

func RegisterEventIngestionServer(s grpc.ServiceRegistrar, srv EventIngestionServer) {
	// If the following call panics, it indicates UnimplementedEventIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestion_ServiceDesc, srv)
}

func _EventIngestion_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngestionServer).StreamEvents(&grpc.GenericServerStream[EventBatch, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestion_StreamEventsServer = grpc.ClientStreamingServer[EventBatch, StreamResponse]

// EventIngestion_ServiceDesc is the grpc.ServiceDesc for EventIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nefi.EventIngestion",
	HandlerType: (*EventIngestionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventIngestion_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/nefi.proto",
}
