apiVersion: v1
kind: Pod
metadata:
  name: bcc-test
  namespace: nefi
spec:
  hostPID: true
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
    - name: bcc-test
      image: ghcr.io/gihongjo/nefi-bcc-test:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
          readOnly: true
        - name: sys-fs-bpf
          mountPath: /sys/fs/bpf
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
  volumes:
    - name: sys-kernel-debug
      hostPath:
        path: /sys/kernel/debug
    - name: sys-fs-bpf
      hostPath:
        path: /sys/fs/bpf
    - name: lib-modules
      hostPath:
        path: /lib/modules
    - name: usr-src
      hostPath:
        path: /usr/src
  restartPolicy: Never
