// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type nefiTraceArgsT struct {
	Buf uint64
	Fd  uint32
	_   [4]byte
}

// loadNefiTrace returns the embedded CollectionSpec for nefiTrace.
func loadNefiTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NefiTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nefiTrace: %w", err)
	}

	return spec, err
}

// loadNefiTraceObjects loads nefiTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nefiTraceObjects
//	*nefiTracePrograms
//	*nefiTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNefiTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNefiTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nefiTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nefiTraceSpecs struct {
	nefiTraceProgramSpecs
	nefiTraceMapSpecs
	nefiTraceVariableSpecs
}

// nefiTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nefiTraceProgramSpecs struct {
	TpSysEnterClose    *ebpf.ProgramSpec `ebpf:"tp_sys_enter_close"`
	TpSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_connect"`
	TpSysEnterRead     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_read"`
	TpSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendto"`
	TpSysEnterWrite    *ebpf.ProgramSpec `ebpf:"tp_sys_enter_write"`
	TpSysExitAccept4   *ebpf.ProgramSpec `ebpf:"tp_sys_exit_accept4"`
	TpSysExitRead      *ebpf.ProgramSpec `ebpf:"tp_sys_exit_read"`
	TpSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitSendto    *ebpf.ProgramSpec `ebpf:"tp_sys_exit_sendto"`
	TpSysExitWrite     *ebpf.ProgramSpec `ebpf:"tp_sys_exit_write"`
}

// nefiTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nefiTraceMapSpecs struct {
	ActiveRecvArgs *ebpf.MapSpec `ebpf:"active_recv_args"`
	ActiveSendArgs *ebpf.MapSpec `ebpf:"active_send_args"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	SocketFds      *ebpf.MapSpec `ebpf:"socket_fds"`
}

// nefiTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nefiTraceVariableSpecs struct {
}

// nefiTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNefiTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nefiTraceObjects struct {
	nefiTracePrograms
	nefiTraceMaps
	nefiTraceVariables
}

func (o *nefiTraceObjects) Close() error {
	return _NefiTraceClose(
		&o.nefiTracePrograms,
		&o.nefiTraceMaps,
	)
}

// nefiTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNefiTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nefiTraceMaps struct {
	ActiveRecvArgs *ebpf.Map `ebpf:"active_recv_args"`
	ActiveSendArgs *ebpf.Map `ebpf:"active_send_args"`
	Events         *ebpf.Map `ebpf:"events"`
	SocketFds      *ebpf.Map `ebpf:"socket_fds"`
}

func (m *nefiTraceMaps) Close() error {
	return _NefiTraceClose(
		m.ActiveRecvArgs,
		m.ActiveSendArgs,
		m.Events,
		m.SocketFds,
	)
}

// nefiTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNefiTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nefiTraceVariables struct {
}

// nefiTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNefiTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nefiTracePrograms struct {
	TpSysEnterClose    *ebpf.Program `ebpf:"tp_sys_enter_close"`
	TpSysEnterConnect  *ebpf.Program `ebpf:"tp_sys_enter_connect"`
	TpSysEnterRead     *ebpf.Program `ebpf:"tp_sys_enter_read"`
	TpSysEnterRecvfrom *ebpf.Program `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterSendto   *ebpf.Program `ebpf:"tp_sys_enter_sendto"`
	TpSysEnterWrite    *ebpf.Program `ebpf:"tp_sys_enter_write"`
	TpSysExitAccept4   *ebpf.Program `ebpf:"tp_sys_exit_accept4"`
	TpSysExitRead      *ebpf.Program `ebpf:"tp_sys_exit_read"`
	TpSysExitRecvfrom  *ebpf.Program `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitSendto    *ebpf.Program `ebpf:"tp_sys_exit_sendto"`
	TpSysExitWrite     *ebpf.Program `ebpf:"tp_sys_exit_write"`
}

func (p *nefiTracePrograms) Close() error {
	return _NefiTraceClose(
		p.TpSysEnterClose,
		p.TpSysEnterConnect,
		p.TpSysEnterRead,
		p.TpSysEnterRecvfrom,
		p.TpSysEnterSendto,
		p.TpSysEnterWrite,
		p.TpSysExitAccept4,
		p.TpSysExitRead,
		p.TpSysExitRecvfrom,
		p.TpSysExitSendto,
		p.TpSysExitWrite,
	)
}

func _NefiTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nefitrace_arm64_bpfel.o
var _NefiTraceBytes []byte
